name: release
on:
  push:
    branches:
      - main
      - development

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Pack nuget
      run: dotnet pack --no-build --configuration Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
    - name: Push nuget
      run: dotnet nuget push "src/Octothorp.AspNetCore.Auth/bin/Release/*.nupkg" --api-key ${{ secrets.NUGETKEY }} --source "https://api.nuget.org/v3/index.json"